#ifndef USTAWIENIA_H
#define USTAWIENIA_H

#define DLUGOSC_DNA 20
#define SZEROKOSC_DNA 20
#define DLUGOSC_WIRNIKA 0.5
#define WYSOKOSC_WIRNIKA 0.5
#define DLUGOSC_KORPUSU 3
#define SZEROKOSC_KORPUSU 2
#define WYSOKOSC_KORPUSU 1

#endif